# Generated by Django 3.1.5 on 2021-01-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queued', models.IntegerField(blank=True, default=0, null=True)),
                ('learning', models.IntegerField(blank=True, default=0, null=True)),
                ('learnt', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
