# Generated by Django 3.1.5 on 2021-01-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210123_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='full_text',
            field=models.TextField(null=True),
        ),
    ]
