# Generated by Django 3.1.5 on 2021-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topic_full_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.AddField(
            model_name='topic',
            name='learning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='learnt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='queued',
            field=models.BooleanField(default=True),
        ),
    ]
