# Generated by Django 3.1.5 on 2021-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210124_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='learnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='queued',
            field=models.BooleanField(default=False),
        ),
    ]
